package-lock.json
package.json
src/Pages/IntroPage.js
src/Pages/RequestPage.js
src/Routes.js

서명자 요청하여 사명자 정보 상태에 저장, 
서명 상태 생성

서명자 요청 기능 구현

---

src/Pages/ReceiveListPage.js
src/Pages/RequestListPage.js

당일 마감기한 스타일 변경

---

public/index.html

웹사이트 로고 및 이름 수정

---

src/Pages/AddSignerPage.js

이메일 입력 셀렉터 기능 추가

---

src/Pages/SetupTaskPage.js

add datepicker date

---

src/Pages/ReceiveListPage.js
src/Pages/RequestListPage.js

[Chore] : 날짜 형태 변경 및 서명 라벨 워딩 변경
변경된 사항)
1. 날짜 형태 변경: yy년 mm월 dd일 -> yyyy/mm/dd
2. 서명 라벨 워딩 변경: 서명 진행중 -> 서명중, 완료됨 -> 완료, 취소됨 -> 취소, 거절됨 -> 거절, 만료됨 -> 만료

[Chore] : 날짜 형태 변경 및 서명 라벨 워딩 변경

---

src/Pages/AddSignerPage.js

[Feat]예시커밋

---

src/Pages/AllocatePage.js

[feat] 서명 인원 카드 추가 및 시각적 분리 

---

src/Pages/ReceiveListPage.js
src/Pages/RequestListPage.js
src/Routes.js

[Fix] : 리스트 머지 오류 수정 

---

src/Pages/ReceiveListPage.js
src/Pages/RequestListPage.js

[Chore] 인덱스 번호 출력 방식 수정 및 서명 완료 시간 로직 추가

[Chore] 인덱스 번호 출력 방식 수정 및 서명 완료 시간 로직 추가

---

src/Layout/Sidebar.js
src/recoil/atom/authState.js

authState에서 관리중인 인증정보를 loginMemberState를 참조하도록 변경

[Fix] 로그인 인증 상태 관리 수정

---

package-lock.json
package.json
src/Pages/DetailPage.js
src/Pages/RequestListPage.js

[feature] 상세보기 페이지 툴바 추가 및 검색 기능 구현

[feature] 상세보기 페이지 툴바 추가 및 검색 기능 구현

---

src/Routes.js
src/recoil/atom/loginMemberState.js
src/utils/RequireLogin.js

loginMemberState: 로딩중 상태값 추가하여, 새로고침시 true로 초기화
RequireLogin: 로그인 상태의 로딩중 값을 조회하고 리디렉션하도록 수정

[Fix]로그인 한 상태에서 로그인 필요한 페이지에서 새로고침시 홈으로 리디렉션 안되도록 수정

---

src/Pages/SetupTaskPage.js
src/components/AllocatePage/CompleteButton.js
src/recoil/atom/taskState.js
src/utils/ApiService.js

수정 사항)
1. 작업 생성시에 TA 근무일지인지 일반 작업 인지 고르고 해당하는 템플릿을 골라서 작업할 수 있게 변경
2. TA 근무일지 작업일 때 과목명 해당월을 선택하면 자동으로 과목명_월_이름_학번으로 작업명이 생성되게 로직 추가

[Feature] 작업 생성시 템플릿 분류 로직 추가

---

src/Layout/Sidebar.js
src/Pages/ReceiveListPage.js
src/Pages/RequestListPage.js

[Chore] 리스트 형태 카트 형태로 변경

---

src/Layout/Sidebar.js
src/Routes.js
src/utils/ApiService.js

[Fix] 머지 후 에러 수정

---

src/Layout/Sidebar.js
src/Pages/AdminListPage.js
src/Pages/DetailPage.js
src/Pages/ReceiveListPage.js
src/Pages/RequestListPage.js

[Feat] 라벨 스타일 변경 및 관리자 페이지 권한 부여

[Feat] 라벨 스타일 변경 및 관리자 페이지 권한 부여

---

src/Pages/AdminListPage.js
src/Pages/ReceiveListPage.js
src/Pages/RequestListPage.js
src/utils/ApiService.js
src/utils/DownloadUtils.js

= AdminListPage: 다운로드 버튼 활성화, 일괄 다운로드 버튼 추가
= Received,RequestPage: 다운로드 버튼 활성화
= APIservice: 다운로드 API 추가
+ DownloadUtils: 한 문서 다운로드, 집파일 다운로드 함수 추가

[FEAT] 다운로드 버튼 활성화 및 다운로드 용 유틸 파일추가

---

package-lock.json
package.json
src/Pages/AdminListPage.js
src/Pages/ReceiveListPage.js
src/Pages/RequestListPage.js

[Feature] 엑셀 파일로 저장 방식 변경 및 요청한 리스트 버튼 추가

[Feature] 엑셀 파일로 저장 방식 변경 및 요청한 리스트 버튼 추가

---

src/Layout/Sidebar.js
src/Pages/CheckPasswordPage.js
src/Pages/CheckTaskPage.js
src/Pages/CompleteSignPage.js
src/Pages/LandingPage.js
src/Pages/ReceiveListPage.js
src/Pages/RequestListPage.js
src/Pages/SetupTaskPage.js
src/Routes.js
src/auth/LoginCallback.js
src/components/ListPage/CancelButton.js
src/components/PagingControl.js
src/components/SignPage/PasswardInputModal.js
src/hooks/useRestoreLoginFromCookie.js
src/styles/animations.css
src/utils/ApiService.js

[FIX] 로그인한 사용자는 리스티에서 서명하기 누를시 서명 안해도 되게 변경
코드 내의 console.log 전부 주석처리

[FIX] 로그인한 사용자는 리스티에서 서명하기 누를시 서명 안해도 되게 변경

---

package-lock.json
package.json
public/index.html
src/App.js
src/styles/GlobalStyle.js

글로벌 스타일에서 임포트하던 나눔고딕링크를 인덱스 html에 옮김

[FIX] 스타일드 컴포넌트 렌터링 오류 수정

---

src/Pages/AdminListPage.js
src/Pages/ReceiveListPage.js
src/Pages/RequestListPage.js
src/components/ListPage/CancelButton.js
src/components/ListPage/CancelModal.js
src/components/ListPage/RejectModal.js

[Chore] 리스트 취소 및 반려 모달 스타일 수정 및 리스트 글씨 색깔 통일

[Chore] 리스트 취소 및 반려 모달 스타일 수정 및 리스트 글씨 색깔 통일 

---

src/Pages/DetailPage.js
src/Pages/ReceiveListPage.js

[Chore] 디테일 페이지 수정 및 공유 작업 페이지 드롭다운 디자인 수정

[Chore] 디테일 페이지 수정 및 공유 작업 페이지 드롭다운 디자인 수정

---

src/Layout/Sidebar.js
src/Pages/DashBoardPage.js
src/Pages/RequestListPage.js
src/components/ConfirmModal.js

대쉬보드 페이지에 문의하기/ 메뉴얼 버튼 추가 및 요청 페이지 내 그리드 보기 워딩 수정.

[feat] add button in page

---

.idea/inspectionProfiles/Project_Default.xml
src/Layout/Sidebar.js
src/Pages/ReceiveListPage.js
src/Pages/RequestListPage.js
src/components/ListPage/CancelModal.js
src/components/ListPage/RejectModal.js

[Chore]리스트 페이지 드롭다운 깨짐 현상 수정

---

src/Pages/AdminListPage.js

[Feature] 관리자 페이지 서명자 정보 모달 추가

[Feature] 관리자 페이지 서명자 정보 모달 추가

---

src/Pages/AdminListPage.js

[Chore]관리자 페이지 리스트 드롭다운 투명화 수정

[Chore]관리자 페이지 리스트 드롭다운 투명화 수정

---

src/Pages/DashBoardPage.js

[FEAT] add 상태: 추가

---

src/Pages/AdminListPage.js
src/Pages/ReceiveListPage.js
src/Pages/RequestListPage.js

[Feature] 드롭다운 문서보기 url 수정

---

src/Routes.js

[FEAT] 사이드바 안 뜨게 변경하다

---

src/Pages/AllocatePage.js

[FEAT] 서명자 카드 수정

---

src/Pages/AllocatePage.js

[FEAT] Card 수정

---

src/Pages/AdminListPage.js
src/components/HisnetLogoutButton.js

[Feature] 필터링 유지 로직 추가

---

src/Pages/AllocatePage.js

[FEAT] 카드 포멧 추가
